### ISSUE TITLE
error loading module 'libcv' from file './libcv.so':

### ISSUE THREAD

**Issue by fengyiliu11** [jzbontar/mc-cnn#24] opened 2017-04-09 02:30 UTC
Hi Jure,

Thanks so much for sharing this code. I am trying to running the code following your instruction. However I get a error when I run the command

./main.lua kitti fast -a predict -net_fname net/net_kitti_fast_-a_train_all.t7 -left samples/input/kittiL.png -right samples/input/kittiR.png -disp_max 70

error loading module 'libcv' from file './libcv.so':
	libcudart.so.7.5: cannot open shared object file: No such file or directory
stack traceback:
	[C]: in function 'error'
	/home/fyl/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	/home/fyl/MC-CNN/main.lua:5: in main chunk
	[C]: in function 'dofile'
	.../fyl/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406050

My CUDA version is 8.0,  then I run the command : ldd libcv.so
Here are the output:
       libcudart.so.7.5 => not found
        libnppc.so.7.5 => not found
        libnppi.so.7.5 => not found
        libnpps.so.7.5 => not found
        libcufft.so.7.5 => not found
        libcudart.so.7.5 => not found
        libnppc.so.7.5 => not found
        libnppi.so.7.5 => not found
        libnpps.so.7.5 => not found
        libcufft.so.7.5 => not found
 
Do you have any suggestions about it? Thanks!

Yiliu

**Comment by jzbontar** [comment] 2017-04-12 19:53
Maybe you had cuda 7.5 installed when you compiled the mc-cnn code and some time later, your system updated your cuda version to 8.0. Try running `make clean` and `make`.

**Comment by fengyiliu11** [comment] 2017-04-13 00:40
@jzbontar  Thank you . The problem is the version of Opencv. Opencv2.4.12 do not support CUDA8.0, but Opencv2.4.13 do.  
I run your code with large input_patch_size, I found the training error decrease, but the final disparity error increase instead. Why, is the season of the parameters of stereo method?

**Comment by fengyiliu11** [comment] 2017-04-13 01:01
@jzbontar Thank you . The problem is the version of Opencv. Opencv2.4.12 do not support CUDA8.0, but Opencv2.4.13 do.

**Comment by jzbontar** [comment] 2017-04-13 14:37
I see. I take it the problem is fixed now?

**Comment by fengyiliu11** [comment] 2017-04-14 03:02
@jzbontar  yes, the code can run successfully

**Closed** 2017-04-17 03:10 UTC
